apiVersion: v1
kind: Pod 
metadata: 
  name: pvc-tester 
  namespace: app 
spec:
  containers:
    - name: busybox 
      image: busybox:1.36 
      command: ["sh","-c", "sleep 3600"]
      volumeMounts: 
        - name: data 
          mountPath: /data 
  
  volumes:
    - name: data 
      PersistentVolumeClaim: 
        claimName: app-pvc 