apiVersion: v1
kind: Service
metadata:
  name: external-dns-test
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: eapp1.mohammadahmed1774.work
spec:
  type: LoadBalancer
  selector:
    app: external-dns-test
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-test
  template:
    metadata:
      labels:
        app: external-dns-test
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
